query GetShop($language: LanguageCode!) @inContext(language: $language) {
  shop {
    name
    description
    brand {
      slogan
      shortDescription
      logo {
        image {
          url
          altText
          width
          height
        }
      }
      squareLogo {
        image {
          url
          altText
          width
          height
        }
      }
      colors {
        primary {
          background
          foreground
        }
        secondary {
          background
          foreground
        }
      }
    }
  }
}
